accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),

]

todos/urls.py
from django.urls import path

from todos import views

app_name = 'todos'
urlpatterns = [
    path('', views.authenticated, name='authenticated'),
    path('create/', views.create_todo, name='create_todo'),
    path('view/<int:todo_id>/', views.view_todo, name='view_todo'),
    path('modify/<int:todo_id>/', views.modify_todo, name='modify_todo'),
    path('delete/<int:todo_id>/', views.delete_todo, name='delete_todo'),
    path('complete_todo/<int:todo_id>/', views.complete_todo, name='complete_todo')
]

todosproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('authenticated/', include('todos.urls'))
]

todos/models.py
from django.db import models

from accounts.models import RegisterUserModel


# Create your models here.
class LabelTodosModel(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'Etiquetas'
        verbose_name = 'Etiqueta'

    def __str__(self):
        return self.name


class TodosUserModel(models.Model):
    STATUS_CHOICES = (
        ('pendiente', 'Pendiente'),
        ('en progreso', 'En progreso'),
        ('completada', 'Completada'),
    )

    user = models.ForeignKey(RegisterUserModel, on_delete=models.CASCADE, verbose_name='Nombre Usuario')
    title = models.CharField(max_length=100, verbose_name='Titulo', blank=True)
    description = models.TextField(verbose_name='Descripcion', blank=True)
    observations = models.TextField(verbose_name='Observaciones', blank=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='pendiente', verbose_name='Estado',
                              blank=True)
    due_date = models.DateField(verbose_name='Fecha de Vencimiento', blank=True)
    labels = models.ManyToManyField(LabelTodosModel, blank=True, verbose_name='Etiquetas')
    priority = models.ForeignKey('PriorityUserModel', on_delete=models.SET_NULL, null=True, verbose_name='Prioridad',
                                 blank=True)

    class Meta:
        verbose_name_plural = 'Tareas'
        verbose_name = 'Tarea'

    def __str__(self):
        return self.title


class PriorityUserModel(models.Model):
    PRIORITY_CHOICES = (
        ('alta', 'Alta'),
        ('media', 'Media'),
        ('baja', 'Baja')
    )
    priority = models.CharField(max_length=50, choices=PRIORITY_CHOICES, default='media', verbose_name='Prioridad')

    def __str__(self):
        return self.priority

    class Meta:
        verbose_name_plural = 'Prioridades'
        verbose_name = 'Prioridad'

todos/forms.py
from django import forms

from accounts.models import RegisterUserModel
from .models import TodosUserModel, LabelTodosModel, PriorityUserModel


class CreateTodoForm(forms.ModelForm):
    labels = forms.ModelMultipleChoiceField(
        queryset=LabelTodosModel.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    user = forms.ModelChoiceField(
        queryset=RegisterUserModel.objects.all(),
        required=False
    )

    priority = forms.ModelChoiceField(
        queryset=PriorityUserModel.objects.all(),
        required=False
    )

    class Meta:
        model = TodosUserModel
        fields = '__all__'


class ViewTodoForm(forms.ModelForm):
    status = forms.ChoiceField(choices=TodosUserModel.STATUS_CHOICES, required=False)
    labels = forms.ModelMultipleChoiceField(queryset=LabelTodosModel.objects.all(), required=False)
    observations = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = TodosUserModel
        fields = ['status', 'labels', 'observations', 'priority']

todos/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect

from .models import TodosUserModel
from .forms import CreateTodoForm, ViewTodoForm


# Create your views here.
@login_required(login_url='accounts:login')
def authenticated(request):
    todos_form = ViewTodoForm(request.GET)
    if todos_form.is_valid():
        status = todos_form.cleaned_data.get('status')
        labels = todos_form.cleaned_data.get('labels')
    else:
        status = 'Pendiente'
        labels = None

    todos = TodosUserModel.objects.filter(user=request.user)

    if status:
        todos = todos.filter(status=status)

    if labels:
        todos = todos.filter(labels__in=labels)

    todos = todos.order_by('due_date')

    return render(request, 'todos/authenticated.html', {'todos': todos, 'todos_form': todos_form})


@login_required(login_url='accounts:login')
def create_todo(request):
    if request.method == 'POST':
        todos_form = CreateTodoForm(request.POST)
        if todos_form.is_valid():
            todo = todos_form.save(commit=False)
            todo.save()
            todos_form.save_m2m()
            messages.success(request, 'Tarea creada correctamente')
            return redirect('todos:authenticated')
    else:
        todos_form = CreateTodoForm()
    return render(request, template_name='todos/create.html', context={'todos_form': todos_form})


@login_required(login_url='accounts:login')
def view_todo(request, todo_id):
    original_todo = TodosUserModel.objects.get(id=todo_id)
    if request.method == 'POST':
        todo_observations = ViewTodoForm(request.POST)
        if todo_observations.is_valid():
            new_observations = todo_observations.cleaned_data['observations']
            if original_todo.observations is None:
                original_todo.observations = new_observations
            else:
                original_todo.observations += "\n" + new_observations
            original_todo.save()
            messages.success(request, 'Observación agregada correctamente')
            return redirect('todos:view_todo', todo_id=todo_id)
    else:
        todo_observations = ViewTodoForm()

    try:
        todo_detail = TodosUserModel.objects.get(id=todo_id)
        return render(request, template_name='todos/view.html',
                      context={'todo_detail': todo_detail, 'todos_observations': todo_observations})
    except TodosUserModel.DoesNotExist:
        return render(request, template_name='todos/view.html')


@login_required(login_url='accounts:login')
def modify_todo(request, todo_id):
    try:
        todo_modify = TodosUserModel.objects.get(id=todo_id)
    except TodosUserModel.DoesNotExist:
        return redirect('todos:authenticated')

    if request.method == 'POST':
        todos_form = CreateTodoForm(request.POST, instance=todo_modify)
        if todos_form.is_valid():
            todo = todos_form.save(commit=False)
            todo.user = request.user
            todo.save()
            todos_form.save_m2m()
            messages.success(request, 'Tarea actualizada correctamente')
            return redirect('todos:authenticated')
    else:
        todos_form = CreateTodoForm(instance=todo_modify)

    return render(request, template_name='todos/modify.html',
                  context={'todos_form': todos_form, 'todo_id': todo_modify.id})


@login_required(login_url='accounts:login')
def complete_todo(request, todo_id):
    todo_complete = TodosUserModel.objects.get(id=todo_id)
    todo_complete.status = 'completada'
    todo_complete.save()
    messages.success(request, 'Tarea completada')
    return redirect('todos:authenticated')


@login_required(login_url='accounts:login')
def delete_todo(request, todo_id):
    todo_delete = TodosUserModel.objects.get(id=todo_id)
    if request.user == todo_delete.user:
        todo_delete.delete()
        messages.success(request, 'Tarea eliminada correctamente')
        return redirect('todos:authenticated')

todos/templates/todos/authenticated.html
{% extends 'todos/base.html' %}
{% load widget_tweaks %}

{% block logout %}
    <a href="{% url 'accounts:logout' %}" class="ms-5 btn btn-outline-success btn-sm">Logout</a>
{% endblock %}

{% block content %}
    <div class="container">
        <h4 class="text-center text-bg-light w-50 mx-auto rounded-3 m-4 p-1">Listado de Tareas</h4>
        {% if messages %}
            <div class="d-flex justify-content-center">
                {% for message in messages %}
                    <div class="alert alert-success w-50 text-center" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <form method="get" class="d-flex justify-content-around mb-4">
            <div class="col-3 text-end me-2">
                {{ todos_form.status|attr:"class:btn btn-secondary dropdown-toggle" }}
            </div>
            <div class="col-3 text-start">
                {{ todos_form.labels|attr:"class:btn btn-secondary dropdown-toggle" }}
            </div>
            <div class="col-6 text-center">
                <a href="{% url 'todos:create_todo' %}" class="btn btn-secondary">Añadir Tarea</a>
            </div>
        </form>

        {% if todos %}
            <table class="table table-striped w-75 mx-auto">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Tarea</th>
                    <th scope="col">Estado</th>
                    <th scope="col">Fecha Vencimiento</th>
                    <th scope="col">Etiquetas</th>
                    <th scope="col">Prioridad</th>
                    <th scope="col">Detalle</th>

                </tr>
                </thead>
                <tbody>
                {% for todo in todos %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ todo.title }}</td>
                        <td>{{ todo.status }}</td>
                        <td>{{ todo.due_date }}</td>
                        <td>
                            {% for label in todo.labels.all %}
                                {{ label }}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </td>
                        {% if todo.priority.priority == 'alta' %}
                            <td class="text-center"><span
                                    class="badge rounded-pill text-bg-danger">{{ todo.priority.priority }}</span>
                            </td>
                        {% endif %}
                        {% if todo.priority.priority == 'media' %}
                            <td class="text-center"><span
                                    class="badge rounded-pill text-bg-warning">{{ todo.priority.priority }}</span>
                            </td>
                        {% endif %}
                        {% if todo.priority.priority == 'baja' %}
                            <td class="text-center"><span
                                    class="badge rounded-pill text-bg-secondary">{{ todo.priority.priority }}</span>
                            </td>
                        {% endif %}
                        <td><a class="btn btn-secondary" href="{% url 'todos:view_todo' todo.id %}">Ver</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p class="text-center">No se encontraron tareas que coincidan con los filtros.</p>
        {% endif %}
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const statusDropdown = document.getElementById('id_status');
            const labelsDropdown = document.getElementById('id_labels');

            statusDropdown.addEventListener('change', function () {
                this.form.submit();
            });

            labelsDropdown.addEventListener('change', function () {
                this.form.submit();
            });
        });
    </script>
{% endblock %}

todos/templates/todos/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'todos/css/style.css' %}">
    <title>Fenix Store</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
    <div class="container-fluid">
        <img class="me-3" src="{% static 'todos/img/fenix.png' %}" alt="Fenix" width="50" height="50">
        <a class="navbar-brand" href="{% url 'accounts:home' %}">Fenix Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0 ">
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control-sm me-2" type="search" placeholder="Buscar productos" aria-label="Search">
                <button class="btn btn-outline-success btn-sm" type="submit">Busqueda</button>
            </form>
            {% block logout %}
            {% endblock %}
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
<footer class="footer py-3 mt-5 bg-light fixed-bottom">
    <div class="container text-center">
        <span class="text-muted"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                      class="bi bi-c-circle me-1" viewBox="0 0 16 16">
  <path d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.146 4.992c-1.212 0-1.927.92-1.927 2.502v1.06c0 1.571.703 2.462 1.927 2.462.979 0 1.641-.586 1.729-1.418h1.295v.093c-.1 1.448-1.354 2.467-3.03 2.467-2.091 0-3.269-1.336-3.269-3.603V7.482c0-2.261 1.201-3.638 3.27-3.638 1.681 0 2.935 1.054 3.029 2.572v.088H9.875c-.088-.879-.768-1.512-1.729-1.512"/>
</svg>Fenix Store 2024</span>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

todos/templates/todos/create.html
{% extends 'todos/base.html' %}
{% load widget_tweaks %}
{% block logout %}
    <a href="{% url 'accounts:logout' %}" class="ms-5 btn btn-outline-success btn-sm">Logout</a>
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="container w-50 mt-5 bg-light rounded-4">
            <div class="row d-flex justify-content-between p-3">
                <div class="col-2">
                    <a class="btn btn-secondary btn-block btn-sm" href="{% url 'todos:authenticated' %}">Volver</a>
                </div>
                <div class="col-6 text-end">
                    <button type="submit" class="btn btn-secondary btn-sm">Crear tarea</button>
                </div>
            </div>
            <div class="p-3">
                <h3 class="text-center">Detalle de tarea</h3>
                <div class="input-group mb-3 mt-3">
                    <span class="input-group-text w-25" id="inputGroup-sizing-default">Título</span>
                    {{ todos_form.title|attr:"class:form-control"|attr:"aria-label:Sizing example input"|attr:"aria-describedby:inputGroup-sizing-default" }}
                </div>
                <div class="input-group">
                    <span class="input-group-text w-25">Descripción</span>
                    {{ todos_form.description|attr:"class:form-control"|attr:"aria-label:With textarea"|attr:"rows:3" }}
                </div>
                <div class="input-group mb-3 mt-3">
                    <label class="input-group-text w-25" for="inputGroupSelect01">Estatus</label>
                    {{ todos_form.status|attr:"class:form-select" }}
                </div>
                <div class="input-group mb-3 mt-3">
                    <label class="input-group-text w-25" for="inputGroupSelect01">Usuario</label>
                    {{ todos_form.user|attr:"class:form-select" }}
                </div>
                <div class="input-group mb-3 mt-3">
                    <label class="input-group-text w-25" for="inputGroupSelect01">Prioridad</label>
                    {{ todos_form.priority|attr:"class:form-select" }}
                </div>
                <div class="input-group mb-3 mt-3">
                    <span class="input-group-text w-25" id="inputGroup-sizing-default">Vencimiento</span>
                    {{ todos_form.due_date|attr:"type:date"|attr:"class:form-control"|attr:"aria-label:Sizing example input"|attr:"aria-describedby:inputGroup-sizing-default" }}
                </div>
                <div class="input-group mb-3 mt-3 p-2 border border-secondary-subtle rounded-2">
                    {{ todos_form.labels|attr:"class:d-inline-flex ms-2" }}
                </div>
            </div>
        </div>
    </form>
{% endblock %}

todos/templates/todos/modify.html
{% extends 'todos/base.html' %}
{% load widget_tweaks %}
{% block logout %}
    <a href="{% url 'accounts:logout' %}" class="ms-5 btn btn-outline-success btn-sm">Logout</a>
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="container w-50 mt-5 bg-light rounded-4">
            <div class="row d-flex justify-content-between p-3">
                <div class="col-2">
                    <a class="btn btn-secondary btn-block btn-sm"
                       href="{% url 'todos:view_todo' todo_id %}">Volver</a>
                </div>
                <div class="col-6 text-end">
                    <button type="submit" class="btn btn-secondary btn-sm">Actualizar tarea</button>
                </div>
            </div>
            <div class="p-3">
                <h3 class="text-center">Actualizar de tarea</h3>
                <div class="input-group mb-3 mt-3">
                    <span class="input-group-text w-25" id="inputGroup-sizing-default">Título</span>
                    {{ todos_form.title|attr:"class:form-control"|attr:"aria-label:Sizing example input"|attr:"aria-describedby:inputGroup-sizing-default" }}
                </div>
                <div class="input-group">
                    <span class="input-group-text w-25">Descripción</span>
                    {{ todos_form.description|attr:"class:form-control"|attr:"aria-label:With textarea"|attr:"rows:3" }}
                </div>
                <div class="input-group mb-3 mt-3">
                    <label class="input-group-text w-25" for="inputGroupSelect01">Estatus</label>
                    {{ todos_form.status|attr:"class:form-select" }}
                </div>
                <div class="input-group mb-3 mt-3">
                    <label class="input-group-text w-25" for="inputGroupSelect01">prioridad</label>
                    {{ todos_form.priority|attr:"class:form-select" }}
                </div>
                <div class="input-group mb-3 mt-3">
                    <span class="input-group-text w-25" id="inputGroup-sizing-default">Vencimiento</span>
                    {{ todos_form.due_date|attr:"class:form-control"|attr:"aria-label:Sizing example input"|attr:"aria-describedby:inputGroup-sizing-default" }}
                </div>
                <div class="input-group mb-3 mt-3 p-2 border border-secondary-subtle rounded-2">
                    {{ todos_form.labels|attr:"class:d-inline-flex ms-2" }}
                </div>
            </div>
        </div>
    </form>
{% endblock %}

todos/templates/todos/view.html
{% extends 'todos/base.html' %}
{% load widget_tweaks %}
{% block logout %}
    <a href="{% url 'accounts:logout' %}" class="ms-5 btn btn-outline-success btn-sm">Logout</a>
{% endblock %}
{% block content %}
    <div class="container w-50 mt-5 bg-light rounded-4">
        <div class="row d-flex justify-content-between p-3">
            <div class="col-2">
                <a class="btn btn-secondary btn-block btn-sm" href="{% url 'todos:authenticated' %}">Volver</a>
            </div>
            <div class="col-6 text-end">
                <a class="btn btn-secondary btn-sm" href="{% url 'todos:modify_todo' todo_detail.id %}">Editar</a>
                <a class="btn btn-secondary btn-sm" href="{% url 'todos:delete_todo' todo_detail.id %}">Eliminar</a>
                <a class="btn btn-secondary btn-sm" href="{% url 'todos:complete_todo' todo_detail.id %}">Completar</a>
            </div>
        </div>
        <div class="p-3">
            <h3 class="text-center">Detalle de tarea</h3>
            <div class="input-group mb-3 mt-3">
                <span class="input-group-text w-25" id="inputGroup-sizing-default-1">Título</span>
                <input type="text" class="form-control" aria-label="Sizing example input"
                       aria-describedby="inputGroup-sizing-default" value="{{ todo_detail.title }}" disabled>
            </div>
            <div class="input-group">
                <span class="input-group-text w-25">Descripción</span>
                <textarea class="form-control" aria-label="With textarea"
                          disabled>{{ todo_detail.description }}</textarea>
            </div>
            <div class="input-group mb-3 mt-3">
                <span class="input-group-text w-25" id="inputGroup-sizing-default-2">Estatus</span>
                <input type="text" class="form-control" aria-label="Sizing example input"
                       aria-describedby="inputGroup-sizing-default" value="{{ todo_detail.status }}" disabled>
            </div>
            <div class="input-group mb-3 mt-3">
                <span class="input-group-text w-25" id="inputGroup-sizing-default-3">Vencimiento</span>
                <input type="text" class="form-control" aria-label="Sizing example input"
                       aria-describedby="inputGroup-sizing-default" value="{{ todo_detail.due_date }}" disabled>
            </div>
            <div class="input-group pb-4 mt-3">
                <span class="input-group-text w-25" id="inputGroup-sizing-default-4">Etiquetas</span>
                {% for label in todo_detail.labels.all %}
                    <input type="text" class="form-control" aria-label="Sizing example input"
                           aria-describedby="inputGroup-sizing-default" value="{{ label }}" disabled>
                {% endfor %}
            </div>
            <div class="input-group mb-3 mt-3">
                <span class="input-group-text w-25" id="inputGroup-sizing-default-2">Prioridad</span>
                <input type="text" class="form-control" aria-label="Sizing example input"
                       aria-describedby="inputGroup-sizing-default" value="{{ todo_detail.priority }}" disabled>
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="input-group">
                    <span class="input-group-text w-25">Observaciones</span>
                    {{ todos_observations.observations|attr:"class:form-control"|attr:"rows:5" }}
                </div>
                <div class="text-end">
                    <button class="btn btn-secondary btn-sm mt-2 mb-2" type="submit">Guardar Observación</button>
                </div>
            </form>
            <div class="input-group">
                <span class="input-group-text w-30">Historial Observaciones</span>
                <textarea class="form-control" rows="5" aria-label="With textarea"
                          disabled>{{ todo_detail.observations }}</textarea>
            </div>

        </div>
    </div>
{% endblock %}