accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),

]

todos/urls.py
from django.urls import path

from todos import views

app_name = 'todos'
urlpatterns = [
    path('', views.authenticated, name='authenticated'),
    path('create/', views.create_todo, name='create_todo'),
    path('view/<int:todo_id>/', views.view_todo, name='view_todo'),
    path('modify/<int:todo_id>/', views.modify_todo, name='modify_todo'),
    path('delete/<int:todo_id>/', views.delete_todo, name='delete_todo'),
    path('complete_todo/<int:todo_id>/', views.complete_todo, name='complete_todo')
]

todosproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('authenticated/', include('todos.urls'))
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class RegisterUserModel(AbstractUser):
    pass

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import RegisterUserModel


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = RegisterUserModel
        fields = ('username', 'email', 'password1', 'password2')


class UserLoginForm(forms.Form):
    username = forms.CharField(label='Nombre de Usuario', min_length=3, max_length=50)
    password = forms.CharField(label='Password', min_length=8, max_length=50)

    class Meta:
        model = UserCreationForm
        fields = ('username', 'password')

accounts/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

from .forms import UserLoginForm, UserRegisterForm


# Create your views here.
def home(request):
    return render(request, template_name='accounts/home.html')


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('todos:authenticated')
            else:
                messages.error(request, message='Usuario o contraseña incorrectos')
    else:
        form = UserLoginForm()
    return render(request, template_name='accounts/login.html', context={'form': form})


def user_logout(request):
    logout(request)
    return redirect('accounts:home')


def user_register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Te has registrado correctamente.')
            return render(request, template_name='accounts/register.html', context={'form': form})
    else:
        form = UserRegisterForm()
    return render(request, template_name='accounts/register.html', context={'form': form})

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
    <title>Fenix Store</title>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
    <div class="container-fluid">
        <img class="me-3" src="{% static 'accounts/img/fenix.png' %}" alt="Fenix" width="50" height="50">
        <a class="navbar-brand" href="{% url 'accounts:home' %}">Fenix Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0 ">
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control-sm me-2" type="search" placeholder="Buscar productos" aria-label="Search">
                <button class="btn btn-outline-success btn-sm" type="submit">Busqueda</button>
            </form>
            {% block logout %}
            {% endblock %}
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
<footer class="footer mt-auto py-3 bg-light fixed-bottom">
    <div class="container text-center">
        <span class="text-muted"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                      class="bi bi-c-circle me-1" viewBox="0 0 16 16">
  <path d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8m15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8.146 4.992c-1.212 0-1.927.92-1.927 2.502v1.06c0 1.571.703 2.462 1.927 2.462.979 0 1.641-.586 1.729-1.418h1.295v.093c-.1 1.448-1.354 2.467-3.03 2.467-2.091 0-3.269-1.336-3.269-3.603V7.482c0-2.261 1.201-3.638 3.27-3.638 1.681 0 2.935 1.054 3.029 2.572v.088H9.875c-.088-.879-.768-1.512-1.729-1.512"/>
</svg>Fenix Store 2024</span>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}
{% block content %}
    <div class="d-flex justify-content-center align-items-center vh-100">
        <div class="card w-50 mb-3">
            <div class="card-body">
                <h5 class="card-title text-center mb-3">Bienvenidos a Fenix Store</h5>
                <div class="d-flex justify-content-center">
                    <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-sm ">Login</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="d-flex justify-content-center align-items-center vh-100">
        <div class="card w-25 h-50">
            <div class="card-body">
                <h5 class="card-title text-center mt-2">Login Fenix Store</h5>
                <div class="d-flex justify-content-center mt-5">
                    <form method="post">
                        {% csrf_token %}
                        {% for message in messages %}
                            <div class="alert alert-danger">{{ message }}</div>
                        {% endfor %}
                        <div class="mb-3">
                            <label for="{{ form.username.id_for_label }}"
                                   class="form-label">{{ form.username.label_tag }}</label>
                            {{ form.username|attr:"class:form-control" }}
                            {% if form.username.errors %}
                                <div class="text-danger">{{ form.username.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="mb-4">
                            <label for="{{ form.password.id_for_label }}"
                                   class="form-label">{{ form.password.label_tag }}</label>
                            {{ form.password|attr:"class:form-control"|attr:"type:password" }}
                        </div>
                        <div class="d-flex justify-content-center">
                            <button type="submit" class="btn btn-secondary btn-sm mt-3">Iniciar sesión</button>
                        </div>
                    </form>
                </div>
                <p class="text-center mt-5">No estas registado, <a href="{% url 'accounts:register' %}">Registrate
                    aca</a></p>
            </div>

        </div>
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <div class="d-flex justify-content-center align-items-center vh-100">
        <div class="card w-50 h-75">
            <div class="card-body">
                <h5 class="card-title text-center mt-3">Registro Usuarios Fenix Store</h5>
                <div class="d-flex justify-content-center mt-5">
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-4">
                            <label for="{{ form.username.id_for_label }}"
                                   class="form-label">{{ form.username.label_tag }}</label>
                            {{ form.username|attr:"class:form-control" }}
                        </div>
                        <div class="mb-4">
                            <label for="{{ form.email.id_for_label }}"
                                   class="form-label">{{ form.email.label_tag }}</label>
                            {{ form.email|attr:"class:form-control" }}
                        </div>
                        <div class="mb-4">
                            <label for="{{ form.password1.id_for_label }}"
                                   class="form-label">{{ form.password1.label_tag }}</label>
                            {{ form.password1|attr:"class:form-control"|attr:"type:password" }}
                        </div>
                        <div class="mb-4">
                            <label for="{{ form.password2.id_for_label }}"
                                   class="form-label">{{ form.password2.label_tag }}</label>
                            {{ form.password2|attr:"class:form-control"|attr:"type:password" }}
                        </div>
                        <div class="d-flex justify-content-center">
                            <button type="submit" class="btn btn-secondary mt-4">Registrarse</button>
                        </div>
                        {% for message in messages %}
                            <div class="alert alert-danger">{{ message }}</div>
                        {% endfor %}
                    </form>
                </div>
            </div>
        </div>
        {% if messages %}
            <div class="modal" tabindex="-1" id="messageModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Fenix Store</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            {% for message in messages %}
                                <p>{{ message }}</p>
                            {% endfor %}
                        </div>
                        <div class="modal-footer">
                            <a href="{% url 'accounts:login' %}" class="btn btn-secondary" id="loginLink"
                               data-bs-dismiss="modal">Cerrar</a>
                        </div>
                    </div>
                </div>
            </div>
            <script>
                document.addEventListener('DOMContentLoaded', function () {
                    var messageModal = new bootstrap.Modal(document.getElementById('messageModal'));
                    messageModal.show();


                    var loginLink = document.getElementById('loginLink');
                    loginLink.addEventListener('click', function (event) {
                        event.preventDefault(); // Evita que el enlace se abra directamente
                        window.location.href = loginLink.getAttribute('href'); // Redirige al enlace de inicio de sesión
                    });
                });
            </script>
        {% endif %}
    </div>
{% endblock %}